### ISSUE TITLE
Wrong implementation of PhotoVoltaics.Components.MultiPhaseConverter

### ISSUE THREAD

**Issue by christiankral** [christiankral/PhotoVoltaics#11]
@luizhrbueno There is a bug in the implementation of the multi phase converter model. It actually revealed the issue when I double checked ``PhotoVoltaics.Examples.SimpleModuleMultiPhase`` based on 37e277f: I added a power sensor on grid side and used power factor = 1 to test the model with varying irradiance input. The power values are then equal.

After changing the power factor to 0.9 (the original value), the gird (real) power is smaller than the PV power. This is wrong.   

The issue is related with performing a phase shift in ``add``. Then the current phasor is calculated with the wrong magnitude as only the phase shift is changed, but ``P = 3*U*I*cos(phi)``

Could you please consider a fix?

**Comment by christiankral** [comment]
OK, I found a solution. The issue was using QuasiRMS voltage and current sensors, as the product of their output, multiplied by 3, equals the apparent power (not real power). Changing this calculation to real power (the converter shall be based on real power balance), the implementation works fine.

**Comment by luizhrbueno** [comment]
The comparison should be with the apparent power, otherwise, the inverter will provide to the system more power that is generated in the PV module. 
For example, for pf=0.9 the module is providing 185W and 90VAr.

![image](https://cloud.githubusercontent.com/assets/25841359/23207931/6dd470f0-f8f3-11e6-8e47-4fb982ebf604.png)

**Comment by christiankral** [comment]
What version of PhotoVoltaics did you create your results with?

Please have a look at b10fdd1 and check out example ``PhotoVoltaics.Examples.SimpleModuleMultiPhase``. In this example 
- DC power
- AC real power
- AC apparent power
- actual power factor are calculated
Everything looks OK, considering, that the ``feedback`` in ``PhotoVoltaics.Components.Converters.MultiPhaseConverter`` is supplied by the real power of the DC and AC side. 
![photovoltaics_ps](https://cloud.githubusercontent.com/assets/4184218/23215578/38e36cfa-f913-11e6-9a4f-0a7a6fc7997b.png)
![photovoltaics_pf](https://cloud.githubusercontent.com/assets/4184218/23215590/448b225a-f913-11e6-9d18-dbc3ede14697.png)

**Comment by luizhrbueno** [comment]
The PV module generates a total power of 185W. This is the maximum power that it can provide to the system (Smax). So the output apparent power (AC) should be equal to the generated power (regardless the losses). Therefore the feedback should be supplied by the apparent power (AC) and not the real power (AC).

Give a look in these two papers for better understanding:

[LF_Stumberger.pdf](https://github.com/christiankral/PhotoVoltaics/files/795987/LF_Stumberger.pdf)
[GSES_powerfactor-110316.pdf](https://github.com/christiankral/PhotoVoltaics/files/795988/GSES_powerfactor-110316.pdf)

**Comment by christiankral** [comment]
The power converter is an ideal DC/AC converter. As we do not consider any loss of converter, input DC power of the PV module needs to be equal the active power of the AC side. This is solely a consequence of the active power balance of any system: active power is a conserved quantity. Consequently, the apparent power of AC side is equal (power factor = 1) or greater than the real power (power factor < 1). 

``powerDC = activePowerAC``
``apparanetPowerAC = activePowerDC / powerFactorAC``

**DC power always equals the active power of the AC side.** The energy meter always counts active power and needs to show the same energy harvest on the DC and AC side of the converter (if the converter is loss free).  

In an ideal case you can supply a purely capacitive or inductive load by an inverter without the need for activePower. So the reactive power is "generated" by the power converter. 

Definitely, It cannot be case, that the DC power and the AC apparent power are equal, except for power factor = 1.

**Comment by luizhrbueno** [comment]
I had a misconception about the inverter. I thought that the apparent output power could not be superior to the DC power.

@christiankral do you think that is required to set a limitation to the apparent power in the converter due to the fact that the real inverters have.

**Comment by christiankral** [comment]
We could limit the current RMS value. This is more physical, as the semiconductors cause the actual (current) limitations. Otherwise, if we limit apparent power, in case we had a small AC voltage, the AC currents would become higher than they would be in a real application.

I will work on an implementation.

**Comment by christiankral** [comment]
OK, As the issue with active and apparent power is fixed in 74a6d1e (version v0.4.0) I will close this ticked and create add the current limitation to #12.
