### ISSUE TITLE
Replace power factor input by reactive power or phase angle input in multi phase converters 

### ISSUE THREAD

**Issue by christiankral** [christiankral/PhotoVoltaics#12]
The transient multi phase inverter model now uses a power factor input. In the actual implementation the reactive power is generated such way, that an inductive load can be supplied. Alternatively, this model shall be adapted that the reactive power or the phase angle ``phi`` shall be used instead of the power factor ``cos(phi)``. This change will then enable to switch from inductive to reactive loads, if required.

@luizhrbueno Do you have a preference: reactive power or phase angle input?

**Comment by luizhrbueno** [comment]
Set of reactive power could be an interesting idea, however, it might cause issues in cases of low irradiation (desired reactive power > power generation). 
I believe that just the phase angle is enough.

**Comment by christiankral** [comment]
As discussed in #11, additionally, an AC current limitation (maximum current ``IACMax``) will be implemented. This feature shall consider the following aspects
- If active power does not exceed the ``IACMax``, reactive power is limited such way that ``IACMax`` is not exceeded
- If active power exceeds ``IACMax``, an assert shall be triggered

**Comment by christiankral** [comment]
I separated the implementation of the phase angle from the implementation of the current limitation (#16).

**Comment by christiankral** [comment]
Implemented phase angle ``phi`` in b1a88aa.
