### ISSUE TITLE
Diode2

### ISSUE THREAD

**Issue by tbeu** [christiankral/PhotoVoltaics#2]
Is PhotoVoltaics.Components.Diode2 comparable to Modelica.Electrical.Analog.Semiconductors.Diode2 of MSL v3.2.2?

**Comment by christiankral** [comment]
The differences compared to Modelica.Electrical.Analog.Semiconductors.Diode2 are for the Diode2 model of the PhotoVoltaics libraray: 
 * Considering temperature dependency of reference point of voltage-current-characteristic
 * No linear region of the conduction and breakdown area
 * No series resistance

**Comment by christiankral** [comment]
The code of the used diode model changed in the meantime, approximating the voltage current characteristics by sections of linear and exponential functions.  So I am wondering if this ticket is still an issue?

**Comment by tbeu** [comment]
No issue.
